export const Epoch = {
  UNIX: 0,
  TWITTER: 1288834974657,
  DISCORD: 1420070400000,
};

export const DEFAULT_VALUE = 0;
export const DEFAULT_SEQUENCE = DEFAULT_VALUE;

export const USIGNED_INCREASE = 1n;
export const SIGNED_INCREASE = -1n;

export const MACHINE_ID_BITS = 16n;
export const SEQUENCE_BITS = 8n;

export const MACHINE_ID_MASK =
  SIGNED_INCREASE ^ (SIGNED_INCREASE << MACHINE_ID_BITS);

export const SEQUENCE_MASK =
  SIGNED_INCREASE ^ (SIGNED_INCREASE << SEQUENCE_BITS);

export const TIMESTAMP_LEFT_SHIFT = SEQUENCE_BITS + MACHINE_ID_BITS;
export const MACHINE_ID_SHIFT = MACHINE_ID_BITS;
